### ISSUE TITLE
"lapack-migration.sh" Is Fundamentally Broken and This Saddens Me

### ISSUE THREAD

**Issue by leycec** [gentoo/sci#897] opened 2018-10-28 02:20 UTC
I'm unconvinced that anyone tested either this script *or* the [installation instructions describing this script](https://github.com/gentoo/sci#blas-and-lapack-migration), which is shamefully bad:

```
$ cd ${EPREFIX}/var/lib/overlays/science/scripts
bash: cd: /var/lib/overlays/science/scripts: No such file or directory
```

## So, It Begins.

`</sigh>`

Very well! Like all self-respecting neckbeards, we use `layman`. Ergo, the installation instructions are entirely inapplicable for the common case. They should instead read:

```
cd "$(portageq get_repo_path / science)/"scripts
./lapack-migration.sh
```

Note the general-purpose `"$(portageq get_repo_path / science)/"` command substitution rather than the hardcoded `${EPREFIX}/var/lib/overlays/science/` dirname. Our shell-shocked horrors only begin there, however:

```
$ ./lapack-migration.sh
bash: ./lapack-migration.sh: Permission denied
```

My mournful sighs are now transmuting into vengeful fist-shaking. The bloody script isn't even executable by default. Of course, its `.sh` filetype is also a blatant lie. This isn't even a Bourne shell script; it's a Bash shell script. So, we now need:

```
$ cd "$(portageq get_repo_path / science)/"scripts
$ bash lapack-migration.sh

Setting Up Eselect for Gentoo Science:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cp: failed to access '/etc/portage/package.mask/': Not a directory
```

**You have got to be friggin' kidding me.** The script erroneously assumes `/etc/portage/package.mask` to be a directory rather than a file, because... testing for file-ness and appending the contents of `sci-lapack` to `/etc/portage/package.mask` if a file is non-trivial, I guess?

I halted there in inconsolable anguish and manually reverted back to [User_talk:Houseofsuns](https://wiki.gentoo.org/wiki/User_talk:Houseofsuns), because I prefer manual sanity to automated insanity. Call me crazy. <sup>*don't, please*</sup>

# omfg

Relatedly, I note this eyebrow-raising package mask in the bundled `sci-lapack` file:

```
## more recently requires (see: https://github.com/gentoo/sci/issues/878 )
>=dev-util/cmake-3.12.0
```

If that isn't super dodgy, I don't know what is.

End users blindly copying these installation instructions will now be inexplicably prevented from installing unrelated packages requiring CMake >= 3.12.0, which is both horrible and mystifying. While I acknowledge #878, silently hard-masking critical system packages without the explicit consent of the current user is *not* an appropriate solution.

The installation instructions need to explicitly inform users of this temporary prerequisite *and* that they will absolutely need to manually undo this hard-mask at a later date – preferably sooner than later.

Thus ends another moral tale of suffering and scientific woe.

**Comment by TheChymera** [comment] 2018-11-16 01:58
@leycec I'd be happy to help you merge any contributions to address the issues you have identified, with one exception, namely that until #878 is fixed or we have moved the mask to the main tree, the mask should remain in place.

If you know of a way to reproduce this bug with the main tree stack alone, I guess getting it merged would be fairly easy.

**Comment by JM1** [comment] 2019-04-09 07:45
Please also add `emerge --oneshot --verbose app-portage/eix >> /dev/null` because `eix` is required by line:
```
FEATURES="-preserve-libs":$FEATURES emerge --oneshot --verbose --exclude sci-libs/blas-reference --exclude sci-libs/cblas-reference --exclude sci-libs/lapack-reference `eix --only-names --installed --in-overlay science`
```

**Comment by TheChymera** [comment] 2019-04-10 03:00
@JM1 Thank you, can you submit a PR? Also, this should be wrapped in a conditional which checks whether eix is absent. Particularyl eix-update may take a bunch of time.

**Closed** 2019-08-08 01:20 UTC
