### ISSUE TITLE
FSL 6.0.2 Version Bump

### ISSUE THREAD

**Issue by TheChymera** [gentoo/sci#929] opened 2019-11-06 22:42 UTC
Dear @kiwifb , it's that time of the year again, and we should maybe bump FSL from the current `5.0.11`, which we make available, to `6.0.2`. I have put together [this basic ported version](https://github.com/TheChymera/overlay/blob/ed14ef2be57abfe3eaf22f6db283cc5d48f44947/sci-biology/fsl/fsl-6.0.2.ebuild), but it fails with the following rather cryptic build log:

```
 * Package:    sci-biology/fsl-6.0.2
 * Repository: chymeric
 * Maintainer: sci-biology@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking fsl-6.0.2.tar.gz to /var/tmp/portage/sci-biology/fsl-6.0.2/work
>>> Source unpacked in /var/tmp/portage/sci-biology/fsl-6.0.2/work
>>> Preparing source in /var/tmp/portage/sci-biology/fsl-6.0.2/work/fsl ...
 * Applying fsl-5.0.11-niftiio_var_fix.patch ...                                                  [ ok ]
 * Applying fsl-5.0.11-ifstream_use.patch ...                                                     [ ok ]
 * Applying fsl-5.0.11-fslsurface_parallel_make.patch ...                                         [ ok ]
 * Applying fsl-5.0.9-headers.patch ...                                                           [ ok ]
 * Adjusting to prefix /
 *   label-div.html ...                                                                           [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sci-biology/fsl-6.0.2/work/fsl ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sci-biology/fsl-6.0.2/work/fsl ...
Building projects - see build.log file for progress...
Build failed to build all projects.
 * ERROR: sci-biology/fsl-6.0.2::chymeric failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 125:  Called src_compile
 *   environment, line 2450:  Called die
 * The specific snippet of code:
 *       ./build || die
 * 
 * If you need support, post the output of `emerge --info '=sci-biology/fsl-6.0.2::chymeric'`,
 * the complete build log and the output of `emerge -pqv '=sci-biology/fsl-6.0.2::chymeric'`.
 * The complete build log is located at '/var/tmp/portage/sci-biology/fsl-6.0.2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-biology/fsl-6.0.2/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-biology/fsl-6.0.2/work/fsl'
 * S: '/var/tmp/portage/sci-biology/fsl-6.0.2/work/fsl'
```

There also doesn't seem to be any other `*.log` I can inspect in the tmep directory.

Can you help me out?
One more thing, as part of the dependency graph, we might be able to unbundle `fslpy`, which is already [in my overlay](https://github.com/TheChymera/overlay/tree/ed14ef2be57abfe3eaf22f6db283cc5d48f44947/dev-python/fslpy), and which I will be adding to Gentoo Science shortly.

**Comment by kiwifb** [comment] 2019-11-06 22:45
OK, I am taking a look.

**Comment by kiwifb** [comment] 2019-11-06 23:49
Right because you didn't try to update `fsl-5.0.11-setup.patch` we don't have any feedback from the build. It is all in `${S}/build.log`. Also several things are broken during the build but the way it is setup the build continue until the end and only reports problems then.

So first stop will be an update on the setup patch.

**Comment by kiwifb** [comment] 2019-11-07 01:46
OK I am doing some more work in a new branch. There are several things I already spotted after the first clean and before the first real breakage. But I will only submit a PR once I have a significant amount of things in.

**Comment by kiwifb** [comment] 2019-11-07 20:26
I have started pushing stuff at https://github.com/kiwifb/overlay/tree/fsl6_moresetup 

This is crazy, no it ships an old version of armadillo-5.200.1 [which is in tree but that version is long gone] which needs lapack. I will have to properly insert blas/lapack next. The code is full of old C++ code that make the default C++ - which should be C++14 by default - spit a lot of garbage about the code.

Because armadillo is wrapped in the aptly named armawrap I don't know we can use a version in tree.

**Comment by kiwifb** [comment] 2019-11-07 23:33
Ported all the old patches. There may still be cruft to eliminate but it is in a much better state now. I'll probably try to disable `mist-clean` which depends on vtk in a first draft. Dealing with vtk may prove difficult so I want to postpone it.

**Comment by TheChymera** [comment] 2019-11-08 06:19
Ok, so fslpy is merged: https://gitweb.gentoo.org/proj/sci.git/commit/?id=6f5e0a4c6026962a3e4b2aef3df2e20ea231b4e5 

Looking more carefully at it, it seems it's used for FSLeyes specifically, but I'm unsure. If FSL proper uses it, it would be really cool to unbundle this as well.

**Comment by kiwifb** [comment] 2019-11-08 06:20
There are still a few kinks probably. I think I may have been overzealous with a couple of things.

**Comment by TheChymera** [comment] 2019-11-08 07:13
@kiwifb my experience with [vtk for ATNs](https://github.com/TheChymera/overlay/blob/master/sci-biology/ants/ants-2.3.1_p20191013.ebuild#L28) has been seamless. So maybe it “just works” here as well?

@pauldmccarthy we're working on version bumping fsl again. I recall there are issues with accepting direct contributions from outside parties for FSL, but maybe you can help us out? Particularly your bundled version of armadillo looks very updated (see [above](https://github.com/gentoo/sci/issues/929#issuecomment-551249210)). Would a newer one work? Also we have a few [patches](https://github.com/kiwifb/overlay/tree/fsl6_moresetup/sci-biology/fsl/files), variations of which we would be very happy if you could consider.

**Comment by kiwifb** [comment] 2019-11-08 07:19
@TheChymera for vtk here I doubt it. But I would have to re-install it and look at it something I moved away from since I have handed paraview's maintenance to someone else some years back.

The only positive I see, is that it looks like a viewer based on something more recent than qt3 (fslview).

Is the armadillo issue a question of licensing? I am prepared to sign over any copyrights on patches of mine that are accepted by the way.

**Comment by pauldmccarthy** [comment] 2019-11-11 14:40
FSL 6.0.3 will be released soon (I don't know when), in which [armawrap](https://git.fmrib.ox.ac.uk/fsl/armawrap) has been updated to use armadillo 9.700. The build system has also been revamped, which may make most of your patches unnecessary.

I have no idea what compiler is used internally - I suspect that it's pre C++11, so would not be surprised if you'r having trouble with C++14. The joys of legacy code.

fslpy, and the fslpython conda environment, are currently only used by a few tools, including FSLeyes, the `im*` scripts, `atlasquery`, and `bianca`. Future versions of FSL will depend more heavily on fslpython.

**Comment by kiwifb** [comment] 2019-11-11 18:54
The makefile settings defines two C++ compilers. CXX and CXX11 if I remember correctly. Which may have made sense 5 years ago but is a bit silly now. I guess we could add `-std=gnu98` or something to CXX but I'd rather see the code standard upped up. Indeed the joys of legacy code!

Good to see some of the internal pieces being updated.

**Comment by pauldmccarthy** [comment] 2019-11-11 19:08
Regarding your [patches](https://github.com/kiwifb/overlay/tree/fsl6_moresetup/sci-biology/fsl/files), are all of the pre-6.0.2 ones obsolete? Or only the ones which are overwritten with a 6.0.2 patch of the same name?

**Comment by kiwifb** [comment] 2019-11-11 19:35
Only the one overwritten with a 6.0.2 patch of the same name. I am not sure they are all in a state of being upstreamed or even if you would wish so. I'd have to look at what is really Gentoo specific.
Because we are trying to use system packages as much as possible one the first patch is to deal with the project lists for example. I would guess you would prefer to be able to switch that behavior on and off rather than straight removal. And then there is the dealing with all the corresponding compilation flags.

**Comment by TheChymera** [comment] 2019-11-14 00:34
@kiwifb The last updated build I pulled from you fails with `ERROR::Could not make meshclass successfully`. Looking at the [build.log](https://github.com/gentoo/sci/files/3844067/build.log), it seems openblas is not being found. Does FSL require openblas specifically? Will it nor work with `sci-libs/blas-reference`?

**Comment by kiwifb** [comment] 2019-11-14 00:38
That flew under my radar. It is doubtful it wouldn't run with something else. I was lucky I was using openblas :) I cannot give you an ETA for a fix but it should be fairly trivial.

**Comment by pauldmccarthy** [comment] 2019-11-14 09:53
@TheChymera Armadillo uses openblas, or blas+lapack. This was one of the big changes in FSL 6.0.0 - switching from [newmat](http://robertnz.net/nm10.htm) to [armadillo](http://arma.sourceforge.net/). In order to avoid having to rewrite large swathes of code which had been using newmat, we wrapped armadillo with armawrap, which is a horrible shim layer that I can't believe actually works.

**Comment by kiwifb** [comment] 2019-11-14 10:33
The worst bit about this, is that the `-lopenblas` in `meshclass` is probably unnecessary. It certainly should be if using dynamic libraries. Provided that armadillo and armawrap have been properly linked, you should only have to include `-lopenblas` if something in `meshclass` uses a blas or lapack function directly.

**Comment by TheChymera** [comment] 2019-11-14 20:47
@kiwifb ok, so having emerged openblas, FSL compiles. Is the fix here as easy as adding it to the dependency list?

This is the files list produced: [fsl_files.txt](https://github.com/gentoo/sci/files/3848575/fsl_files.txt).
@pauldmccarthy does this look complete to you?

**Comment by TheChymera** [comment] 2019-11-14 21:35
@kiwifb In the interest of determining more easily if we're producing a sufficiently good installation, do you think it's feasible to implement the test suite at this point?

**Comment by kiwifb** [comment] 2019-11-14 22:08
I guess we should have a go at looking at the test suite. Note that the current install is missing `mist-clean` by design since I need to figure out the handling of vtk properly. If it has an upstream other than fsl, it may be best to bring it as a separate package.

**Comment by TheChymera** [comment] 2019-11-15 01:16
@kiwifb ok, the new version worked as well, and without openblas. It does, however, produce a significantly different set of files.

See the new set of files: 
[fsl_files_new.txt](https://github.com/gentoo/sci/files/3849386/fsl_files_new.txt)

And the diff versus the old list I pasted above:
[fsl_files_diff.txt](https://github.com/gentoo/sci/files/3849388/fsl_files_diff.txt)

**Comment by kiwifb** [comment] 2019-11-15 01:45
Can you do a `diff -u` I don't grok plain `diff` very well.

**Comment by pauldmccarthy** [comment] 2019-11-15 15:55
I compared your first list against the `$FSLDIR/bin/` directory of a vanilla FSL 6.0.2 installation (I didn't check the other files).

It looks like pretty much everything is there, apart from various items which I presume you know about:
 - all executables provided by the `fslpython` environment (e.g. `imcp`, `fsleyes`, `atlasquery`)
 - mist
 - The GPU tools - `eddy`, `probtrackx_gpu`, `bedpostx_gpu`, and associated utiliites
 -

**Comment by TheChymera** [comment] 2019-11-15 23:19
@kiwifb [fsl_files_diff.txt](https://github.com/gentoo/sci/files/3853493/fsl_files_diff.txt)

@pauldmccarthy just to reiterate, fslpy is not required by fsl, it's a separate package supporting fsleyes, or am I misunderstanding the local dependency graph? Actually, if you have a small dot file describing the relationships between the different components that would be really cool! :)

**Comment by pauldmccarthy** [comment] 2019-11-18 15:30
@TheChymera Sorry for the delay, I've been moving house. 

`fslpy` is required by FSL - currently it just provides (I think) `im*`, `atlasq`, `atlasquery`, and `fsl_ents`. It is also a dependency of FSLeyes (assuming that FSLeyes is installed into the same python environment, rather than being installed as a standalone build). But it will probably provide, and be required by, more tools in the future.

The `fslpython` miniconda environment is part of an ongoing internal effort to migrate the codebase away from Bash and TCL/TK to Python. So in the future, more elements of FSL (including non-python parts) are likely to be installed into the miniconda environment. 

So it's all a bit of a mess right now - in a normal FSL installation, most things are installed from the downloaded tarball. But a handful of tools are installed into, and linked from, the miniconda environment. A possible future scenario is that *all* of FSL will be installed via miniconda.

**Comment by pauldmccarthy** [comment] 2019-11-18 15:32
By the way, FSL 6.0.3 will probably be released in the next few weeks; this is going to be a minor update, so it shouldn't cause you much trouble. I do intend to go through your patches when I get a chance, but I won't be able to get this done in time for 6.0.3.

**Closed** 2020-08-06 04:10 UTC
